version: "3.7"

services:
  sender1:
    build:
      context: .
    cap_add:
      - NET_ADMIN
    networks:
      network_s1_R:
        ipv4_address: 10.1.0.2
    extra_hosts:
      - "receiver1:10.3.0.2"
      - "receiver2:10.4.0.2"
    entrypoint: /root/scripts/startup/sender1.sh
    expose:
      - 22
    volumes:
      - ./src/scripts:/root/scripts

  sender2:
    build:
      context: .
    cap_add:
      - NET_ADMIN
    networks:
      network_s2_R:
        ipv4_address: 10.2.0.2
    extra_hosts:
      - "receiver1:10.3.0.2"
      - "receiver2:10.4.0.2"
    entrypoint: /root/scripts/startup/sender2.sh
    expose:
      - 22
    volumes:
      - ./src/scripts:/root/scripts

  router:
    build:
      context: .
    cap_add:
      - NET_ADMIN
    networks:
      network_s1_R:
        ipv4_address: 10.1.0.11
      network_s2_R:
        ipv4_address: 10.2.0.11
      network_R_r1:
        ipv4_address: 10.3.0.11
      network_R_r2:
        ipv4_address: 10.4.0.11
    entrypoint: /root/scripts/startup/router.sh
    expose:
      - 22
    volumes:
      - ./src/scripts:/root/scripts

  receiver1:
    build:
      context: .
    cap_add:
      - NET_ADMIN
    networks:
      network_R_r1:
        ipv4_address: 10.3.0.2
    entrypoint: /root/scripts/startup/receiver1.sh
    expose:
      - 22
    volumes:
      - ./src/scripts:/root/scripts

  receiver2:
    build:
      context: .
    cap_add:
      - NET_ADMIN
    networks:
      network_R_r2:
        ipv4_address: 10.4.0.2
    entrypoint: /root/scripts/startup/receiver2.sh
    expose:
      - 22
    volumes:
      - ./src/scripts:/root/scripts

networks:
  #sX->senderX rX->receiverX R->Router    
  network_s1_R:
    driver: bridge
    ipam:
      config:
        - subnet: 10.1.0.0/16
  network_s2_R:
    driver: bridge
    ipam:
      config:
        - subnet: 10.2.0.0/16

  network_R_r1:
    driver: bridge
    ipam:
      config:
        - subnet: 10.3.0.0/16
  network_R_r2:
    driver: bridge
    ipam:
      config:
        - subnet: 10.4.0.0/16
